// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'firebase_options.dart';
import 'package:firebase_core/firebase_core.dart' 
show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCg-VAeH2z7OFV6uyOsXCeSeIKfI9NVS2k',
    appId: '1:614623564680:web:4c82571e3ff9666d52e03d',
    messagingSenderId: '614623564680',
    projectId: 'tanicerdas-250cd',
    authDomain: 'tanicerdas-250cd.firebaseapp.com',
    storageBucket: 'tanicerdas-250cd.firebasestorage.app',
    measurementId: 'G-6F8G6W4V2C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2SCB5CbNMHK1Nn_8WhEAOSCJYmt12nis',
    appId: '1:614623564680:android:2b1e4b17cb0a731552e03d',
    messagingSenderId: '614623564680',
    projectId: 'tanicerdas-250cd',
    storageBucket: 'tanicerdas-250cd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsw0vfL4qNzpEUTo1qDLVa5ZdHZVU8F-Q',
    appId: '1:614623564680:ios:443508b8f0fea4d852e03d',
    messagingSenderId: '614623564680',
    projectId: 'tanicerdas-250cd',
    storageBucket: 'tanicerdas-250cd.firebasestorage.app',
    iosBundleId: 'com.example.tanicerdas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsw0vfL4qNzpEUTo1qDLVa5ZdHZVU8F-Q',
    appId: '1:614623564680:ios:443508b8f0fea4d852e03d',
    messagingSenderId: '614623564680',
    projectId: 'tanicerdas-250cd',
    storageBucket: 'tanicerdas-250cd.firebasestorage.app',
    iosBundleId: 'com.example.tanicerdas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCg-VAeH2z7OFV6uyOsXCeSeIKfI9NVS2k',
    appId: '1:614623564680:web:18ae626e712c8cf452e03d',
    messagingSenderId: '614623564680',
    projectId: 'tanicerdas-250cd',
    authDomain: 'tanicerdas-250cd.firebaseapp.com',
    storageBucket: 'tanicerdas-250cd.firebasestorage.app',
    measurementId: 'G-V9F8W0S1K5',
  );
}
